version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '02:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      babel-dependencies:
        patterns:
          - '*babel*'
    ignore:
      # require node > 16
      - dependency-name: glob
        versions:
          - '>= 9.0.0'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '02:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 10
